### ISSUE TITLE
NPE on SignatureEcBc.recoverPublicKey

### ISSUE THREAD

**Issue by hohwille** [m-m-m/crypto#1]
```
java.lang.NullPointerException
	at net.sf.mmm.crypto.asymmetric.sign.ec.bc.SignatureEcBc.recoverPublicKey(SignatureEcBc.java:210)
	at net.sf.mmm.crypto.asymmetric.sign.ec.bc.SignatureEcBc.recoverPublicKey(SignatureEcBc.java:160)
	at net.sf.mmm.crypto.asymmetric.sign.ec.bc.SignatureEcBcWithRecoveryId.recoverPublicKey(SignatureEcBcWithRecoveryId.java:109)
```

Problem occurs if signature has been recovered from binary data and components `R` and `S` have not yet been initialized (lazy init bug).

**Comment by hohwille** [comment]
fixed in `1.0.0-beta4`.
